name: Generate Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Build with Maven
      run: mvn clean install
      
    - name: Install MkDocs
      run: |
        python3 -m pip install --upgrade pip
        pip install mkdocs mkdocs-material

    - name: Generate Documentation
      run: |
        chmod +x ./generate_docs.sh
        ./generate_docs.sh

    - name: Create mkdocs.yml
      run: |
        echo "site_name: Webslate - Java Basics" > docs/mkdocs.yml
        echo "theme:" >> docs/mkdocs.yml
        echo "  name: material" >> docs/mkdocs.yml
        echo "" >> docs/mkdocs.yml
        echo "nav:" >> docs/mkdocs.yml
        echo "  - Home: index.md" >> docs/mkdocs.yml
        # Add additional nav items based on generated Markdown files
        for file in docs/*.md; do
            if [[ "$file" != "docs/index.md" ]]; then
                file_name=$(basename "$file" .md)
                echo "  - $file_name: $file_name.md" >> docs/mkdocs.yml
            fi
        done

    - name: Build MkDocs Site
      run: |
        cd docs  # Change directory to where mkdocs.yml is located
        mkdocs build  # This will generate the site in site directory

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/site  # Publish from the site generated by MkDocs
        keep_files: true
