name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Update to the latest version

    - name: Set up JDK 17  # Update to Java 17
      uses: actions/setup-java@v3  # Update to the latest version
      with:
        java-version: '17'  # Change to 17
        distribution: 'adopt'
        
    - name: Build and test with Maven
      run: mvn clean verify org.jacoco:jacoco-maven-plugin:report
      
    - name: Publish Test Report
      uses: actions/upload-artifact@v3  # Update to the latest version
      if: success() || failure()
      with:
        name: test-report
        path: target/site/jacoco/
        
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: target/surefire-reports/*.xml
